name: "Format Codebase"

on:
  push:
    paths:
      - "assets/**"
      - "layouts/**"
      - "scripts/**"
      - "content/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pyproject.toml"
  workflow_run:
    workflows: ["Build Documentation"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format codebase
        run: pnpm run format

      - name: Format Python code
        uses: astral-sh/ruff-action@v3
      - run: ruff check --fix scripts/
      - run: ruff format scripts/

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          pull: "--rebase --autostash"
          default_author: github_actions
          message: "style: format code"
