name: "Format Codebase"

permissions:
  contents: write

on:
  pull_request:
  push:
    paths:
      - "assets/**"
      - "layouts/**"
      - "scripts/**"
      - "content/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pyproject.toml"
      - ".github/workflows/format.yaml"
  workflow_run:
    workflows: ["Build Documentation"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set branch name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format codebase
        run: pnpm run format

      - name: Format Python code
        uses: astral-sh/ruff-action@v3
      - run: ruff check --fix scripts/
      - run: ruff format scripts/

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "style: format code" || exit 0
          git push origin HEAD:refs/heads/$BRANCH
